before_script:
    - chmod +x code/tests/install_CUnit
    - cd code/tests
    - ./install_CUniti
    - make

prompt:
    script:
        - ./testPrompt

explorer:
    script:
        - ./testExp

after_script:
    - make clean
