before_script:
    - chmod +x code/tests/install_CUnit
    - cd code/tests
    - ./install_CUnit

prompt:
    script:
        - cd code/tests
        - ls 
        - make
        - ./test
        - make clean